apiVersion: v1
kind: Namespace
metadata:
  name: opa-example
  labels:
    accesserator-webhooks: enabled
    istio.io/rev: default
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: app
  namespace: opa-example
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  podSettings:
    annotations:
      accesserator.kartverket.no/verify-securityconfig: "true"
      accesserator.kartverket.no/services: "opa"
  replicas: 1
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config
  namespace: opa-example
spec:
  opa:
    enabled: true
    bundleUrls:
      - name: opa-bundle-1
        url: ghcr.io/kartverket/accesserator/opa-bundle:sha-2694ecfda47ac082b141d73199853f410a92d3c3
  applicationRef: app