apiVersion: v1
kind: Namespace
metadata:
  name: opa-example
  labels:
    skip.kartverket.no/skip-managed: "true"
    istio.io/rev: default
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: app
  namespace: opa-example
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  podSettings:
    annotations:
      accesserator.kartverket.no/verify-securityconfig: "true"
      accesserator.kartverket.no/services: "opa"
  replicas: 1
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config
  namespace: opa-example
spec:
  opa:
    enabled: true
    bundleUrls:
      - name: test-bundle
        url: ghcr.io/kartverket/accesserator/opa-bundle:setup-cosign-verification
        verification:
          source:
            repository: kartverket/accesserator
            workflow: .github/workflows/build-and-push-opa-bundle.yml
            ref: refs/pull/73/merge
  applicationRef: app