apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accesserator
  title: Accesserator
  tags:
    - public
spec:
  type: ops
  owner: group:default/tilgangsstyring
  lifecycle: production
  system: system:default/skip
  dependsOn:
    - component:default/skip-apps
