FROM golang:1.26.4-alpine3.23@sha256:18b460dd17542c2ba43299a633cf6ebfc1115101509531471d7cfce1019af083 AS base
# Needed for ca-certs

FROM scratch

COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY accesserator /accesserator
USER 65532:65532
ENTRYPOINT ["/accesserator"]