apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/deployment.yaml
- base/leader-election-role.yaml
- base/leader-election-rolebinding.yaml
- base/netpol.yaml
- base/pdb.yaml
- base/podmonitor.yaml
- base/serviceaccount.yaml
- base/clusterrolebinding.yaml
- base/service.yaml
- base/webhook-certificate.yaml
- base/webhook-issuer.yaml

images:
- name: controller
  newName: accesserator
  newTag: latest

configMapGenerator:
- envs:
  - base/.env
  name: accesserator-env
  namespace: accesserator-system