//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha

import (
	v1 "github.com/nais/liberator/pkg/apis/nais.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyClient) DeepCopyInto(out *AccessPolicyClient) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(ResourceName)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyClient.
func (in *AccessPolicyClient) DeepCopy() *AccessPolicyClient {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicySpec) DeepCopyInto(out *AccessPolicySpec) {
	*out = *in
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]AccessPolicyClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicySpec.
func (in *AccessPolicySpec) DeepCopy() *AccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedAudience) DeepCopyInto(out *AllowedAudience) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueFrom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedAudience.
func (in *AllowedAudience) DeepCopy() *AllowedAudience {
	if in == nil {
		return nil
	}
	out := new(AllowedAudience)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAdApplicationSpec) DeepCopyInto(out *AzureAdApplicationSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]v1.AzureAdGroup, len(*in))
		copy(*out, *in)
	}
	if in.PreAuthorizedApplications != nil {
		in, out := &in.PreAuthorizedApplications, &out.PreAuthorizedApplications
		*out = make([]v1.AccessPolicyInboundRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReplyUrls != nil {
		in, out := &in.ReplyUrls, &out.ReplyUrls
		*out = make([]v1.AzureAdReplyUrl, len(*in))
		copy(*out, *in)
	}
	if in.SinglePageApplication != nil {
		in, out := &in.SinglePageApplication, &out.SinglePageApplication
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAdApplicationSpec.
func (in *AzureAdApplicationSpec) DeepCopy() *AzureAdApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(AzureAdApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleSource) DeepCopyInto(out *BundleSource) {
	*out = *in
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(BundleSourceVerification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleSource.
func (in *BundleSource) DeepCopy() *BundleSource {
	if in == nil {
		return nil
	}
	out := new(BundleSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleSourceVerification) DeepCopyInto(out *BundleSourceVerification) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleSourceVerification.
func (in *BundleSourceVerification) DeepCopy() *BundleSourceVerification {
	if in == nil {
		return nil
	}
	out := new(BundleSourceVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntraIDSpec) DeepCopyInto(out *EntraIDSpec) {
	*out = *in
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(AzureAdApplicationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientRef != nil {
		in, out := &in.ClientRef, &out.ClientRef
		*out = new(ResourceRef)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntraIDSpec.
func (in *EntraIDSpec) DeepCopy() *EntraIDSpec {
	if in == nil {
		return nil
	}
	out := new(EntraIDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositorySource) DeepCopyInto(out *GitHubRepositorySource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositorySource.
func (in *GitHubRepositorySource) DeepCopy() *GitHubRepositorySource {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositorySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdPortenSpec) DeepCopyInto(out *IdPortenSpec) {
	*out = *in
	in.AllowedAudience.DeepCopyInto(&out.AllowedAudience)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdPortenSpec.
func (in *IdPortenSpec) DeepCopy() *IdPortenSpec {
	if in == nil {
		return nil
	}
	out := new(IdPortenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyRef) DeepCopyInto(out *KeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyRef.
func (in *KeyRef) DeepCopy() *KeyRef {
	if in == nil {
		return nil
	}
	out := new(KeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskinportenClientSpec) DeepCopyInto(out *MaskinportenClientSpec) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = new(MaskinportenScope)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskinportenClientSpec.
func (in *MaskinportenClientSpec) DeepCopy() *MaskinportenClientSpec {
	if in == nil {
		return nil
	}
	out := new(MaskinportenClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskinportenScope) DeepCopyInto(out *MaskinportenScope) {
	*out = *in
	if in.ConsumedScopes != nil {
		in, out := &in.ConsumedScopes, &out.ConsumedScopes
		*out = make([]v1.ConsumedScope, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskinportenScope.
func (in *MaskinportenScope) DeepCopy() *MaskinportenScope {
	if in == nil {
		return nil
	}
	out := new(MaskinportenScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskinportenSpec) DeepCopyInto(out *MaskinportenSpec) {
	*out = *in
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(MaskinportenClientSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientRef != nil {
		in, out := &in.ClientRef, &out.ClientRef
		*out = new(ResourceRef)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskinportenSpec.
func (in *MaskinportenSpec) DeepCopy() *MaskinportenSpec {
	if in == nil {
		return nil
	}
	out := new(MaskinportenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpaBundleSource) DeepCopyInto(out *OpaBundleSource) {
	*out = *in
	if in.BundleNames != nil {
		in, out := &in.BundleNames, &out.BundleNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpaBundleSource.
func (in *OpaBundleSource) DeepCopy() *OpaBundleSource {
	if in == nil {
		return nil
	}
	out := new(OpaBundleSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenPolicyAgentSpec) DeepCopyInto(out *OpenPolicyAgentSpec) {
	*out = *in
	if in.BundleURLs != nil {
		in, out := &in.BundleURLs, &out.BundleURLs
		*out = make([]BundleSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenPolicyAgentSpec.
func (in *OpenPolicyAgentSpec) DeepCopy() *OpenPolicyAgentSpec {
	if in == nil {
		return nil
	}
	out := new(OpenPolicyAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
	out.ClientID = in.ClientID
	out.ClientJWK = in.ClientJWK
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigList) DeepCopyInto(out *SecurityConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigList.
func (in *SecurityConfigList) DeepCopy() *SecurityConfigList {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigSpec) DeepCopyInto(out *SecurityConfigSpec) {
	*out = *in
	if in.Tokenx != nil {
		in, out := &in.Tokenx, &out.Tokenx
		*out = new(TokenXSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Maskinporten != nil {
		in, out := &in.Maskinporten, &out.Maskinporten
		*out = new(MaskinportenSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EntraID != nil {
		in, out := &in.EntraID, &out.EntraID
		*out = new(EntraIDSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Idporten != nil {
		in, out := &in.Idporten, &out.Idporten
		*out = new(IdPortenSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Opa != nil {
		in, out := &in.Opa, &out.Opa
		*out = new(OpenPolicyAgentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigSpec.
func (in *SecurityConfigSpec) DeepCopy() *SecurityConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfigStatus) DeepCopyInto(out *SecurityConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OpaBundleSource != nil {
		in, out := &in.OpaBundleSource, &out.OpaBundleSource
		*out = new(OpaBundleSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfigStatus.
func (in *SecurityConfigStatus) DeepCopy() *SecurityConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenXSpec) DeepCopyInto(out *TokenXSpec) {
	*out = *in
	if in.AccessPolicy != nil {
		in, out := &in.AccessPolicy, &out.AccessPolicy
		*out = new(AccessPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenXSpec.
func (in *TokenXSpec) DeepCopy() *TokenXSpec {
	if in == nil {
		return nil
	}
	out := new(TokenXSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFrom) DeepCopyInto(out *ValueFrom) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(KeyRef)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(KeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFrom.
func (in *ValueFrom) DeepCopy() *ValueFrom {
	if in == nil {
		return nil
	}
	out := new(ValueFrom)
	in.DeepCopyInto(out)
	return out
}
