---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accesserator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - accesserator.kartverket.no
  resources:
  - securityconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accesserator.kartverket.no
  resources:
  - securityconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - accesserator.kartverket.no
  resources:
  - securityconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - nais.io
  resources:
  - azureadapplications
  - jwkers
  - maskinportenclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  - serviceentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skiperator.kartverket.no
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
