apiVersion: v1
kind: Namespace
metadata:
  name: entraid-example
  labels:
    skip.kartverket.no/skip-managed: "true"
    istio.io/rev: default
---
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: test-app
  namespace: entraid-example
spec:
  secretName: entraid-secret
---
