apiVersion: v1
kind: Namespace
metadata:
  name: tokenx-example
  labels:
    skip.kartverket.no/skip-managed: "true"
    istio.io/rev: default
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: app
  namespace: tokenx-example
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  podSettings:
    annotations:
      accesserator.kartverket.no/verify-securityconfig: "true"
      accesserator.kartverket.no/services: "texas"
  replicas: 1
  accessPolicy:
    outbound:
      rules:
        - application: another-app
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config-app
  namespace: tokenx-example
spec:
  tokenx:
    enabled: true
  applicationRef: app
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: another-app
  namespace: tokenx-example
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  podSettings:
    annotations:
      accesserator.kartverket.no/verify-securityconfig: "true"
  replicas: 1
  accessPolicy:
    inbound:
      rules:
        - application: app
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config-another-app
  namespace: tokenx-example
spec:
  tokenx:
    enabled: true
  applicationRef: another-app