apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: jwker
  name: jwker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jwker
subjects:
  - kind: ServiceAccount
    name: jwker
    namespace: jwker-system