apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    webhooks: enabled
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-system-to-accesserator-webhook
  namespace: accesserator-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 443
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: app
  namespace: test
  labels:
    skiperator/security: "enabled"
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  replicas: 1
  accessPolicy:
    outbound:
      rules:
        - application: tokendings
          namespace: obo
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config
  namespace: test
spec:
  tokenx: true
  applicationRef: app
---
apiVersion: nais.io/v1
kind: Jwker
metadata:
  name: app-jwker
  namespace: test
spec:
  accessPolicy:
    inbound:
      rules:
        - application: app-jwker
          namespace: test
          cluster: kind-kind
    outbound:
      rules:
        - application: app-jwker
          namespace: test
          cluster: kind-kind
  secretName: app-jwker-secret