apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/deployment.yaml
  - base/leader-election-role.yaml
  - base/leader-election-rolebinding.yaml
  - base/netpol.yaml
  - base/pdb.yaml
  - base/serviceaccount.yaml
  - base/podmonitor.yaml
patches:
  - target:
      kind: Deployment
      name: jwker
      namespace: jwker-system
    path: patches/deployment.yaml
images:
  - name: ghcr.io/nais/jwker
    newTag: 2026-09-29-125429-87569d1@sha256:69e443aba2fb7ca12cf35fdb9352d01a3aea66c40e58f112fd654ccb8279f8ef
