apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/application.yaml
  - base/authorizationpolicy.yaml
  - base/configmap.yaml
  - base/netpol.yaml

patches:
  - target:
      group: skiperator.kartverket.no
      version: v1alpha1
      kind: Application
      name: tokendings
    path: patches/application.yaml

configurations:
  - configurations/skiperator-application-image-config.yaml

images:
  - name: ghcr.io/nais/tokendings
    newTag: 2026-05-07-113310-0c70186
    digest: sha256:3a5f0f6dae9e4c44f14331d985c66d98943913fa3c896e5cb395af9b7251db5f