apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/application.yaml
  - base/authorizationpolicy.yaml
  - base/configmap.yaml
  - base/netpol.yaml

patches:
  - target:
      group: skiperator.kartverket.no
      version: v1alpha1
      kind: Application
      name: tokendings
    path: patches/application.yaml

configurations:
  - configurations/skiperator-application-image-config.yaml

images:
  - name: ghcr.io/nais/tokendings
    newTag: 2026-05-18-132705-e3718e2
    digest: sha256:bf3857120c597ff1009f29c7de64707614d8f9848b7b955bddb75ee008cac11c
