apiVersion: v1
kind: Namespace
metadata:
  name: idporten-example
  labels:
    skip.kartverket.no/skip-managed: "true"
    istio.io/rev: default
---
apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: app
  namespace: idporten-example
spec:
  image: nginxinc/nginx-unprivileged:latest
  port: 8080
  podSettings:
    annotations:
      accesserator.kartverket.no/verify-securityconfig: "true"
      accesserator.kartverket.no/services: "texas"
  replicas: 1
---
apiVersion: accesserator.kartverket.no/v1alpha
kind: SecurityConfig
metadata:
  name: security-config
  namespace: idporten-example
spec:
  idporten:
    enabled: true
    allowedAudience:
      value: my-idporten-client-id
  applicationRef: app
