name: Build OPA bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: kartverket/github-workflows/.github/workflows/build-and-push-opa-rules.yml@8f2e58e1deb2e50de341dbda2b330b692a2bd92a
    with:
      name: ${{ github.repository }}/opa-bunde
      rego-path: .opa
      test-path: .opa
      additional-tags: |
        ${{ github.ref == 'refs/heads/main' && 'latest' || '' }}