name: Build OPA bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: kartverket/github-workflows/.github/workflows/build-and-push-opa-rules.yml@7eaefaaa8563c3be84ca212b70b7366e10ee67de
    with:
      name: my-opa-bundle
      rego-path: .opa
      test-path: .opa
      additional-tags: |
        ${{ github.ref == 'refs/heads/main' && 'latest' || '' }}