name: Run Chainsaw Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: probe token access
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker manifest inspect ghcr.io/kartverket/tokenx-token-generator-backend/opa-policies@sha256:21afafe09aba8a68a7d002e2ec8e36de0d09b0b96f87e81b434341945657cad2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Install kubefwd
        shell: bash
        run: |
          curl -L https://github.com/txn2/kubefwd/releases/download/v1.25.12/kubefwd_Linux_x86_64.tar.gz | tar xz
          sudo mv kubefwd /usr/local/bin/

      - name: Setup Kind cluster and deploy accesserator
        run: |
          make local deploy mock-oauth2-ingress
          
      - name: Create ghcr secret
        run: |
          kubectl create secret docker-registry github-auth \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --namespace=accesserator-system \
            --dry-run=client -o yaml | kubectl apply -f -
          kubectl rollout restart deploy/accesserator -n accesserator-system
          kubectl rollout status deploy/accesserator -n accesserator-system
      - name: Run Chainsaw tests
        run: |
          make chainsaw-test-all
